### ISSUE TITLE
Update to 1.16.2

### ISSUE THREAD

**Issue by koppen** [koppen/the-distance#1]
https://github.com/PaperMC/Paper/pull/4123

> UNSURE OF DATA INTEGRITY - Please test and ensure your Villages, Pillager Outposts and Bastions are converting from old versions correctly. This includes 1.16.1 too.

> ENSURE YOU HAVE A BACKUP OF ALL WORLDS BEFORE STARTING YOUR SERVER WITH 1.16.2 BUILDS

**Comment by koppen** [comment]
Paper has been upgraded to 1.16.2 (build 174), but Dynmap is broken:

```
02.09 23:10:10 [Multicraft] Starting server!
02.09 23:10:10 [Multicraft] Loaded config for "PaperSpigot 1.16.2"
02.09 23:10:10 [Multicraft] Failed to create local JAR directory
02.09 23:10:10 [Multicraft] JAR file not found, copying from global JAR directory
02.09 23:10:10 [Multicraft] Updating eula.txt file
02.09 23:10:11 [Server] INFO Downloading vanilla jar...
02.09 23:10:12 [Server] INFO Patching vanilla jar...
02.09 23:10:15 [Server] INFO System Info: Java 1.8 (OpenJDK 64-Bit Server VM 25.252-b09) Host: Linux 4.19-ovh-xxxx-std-ipv6-64 (amd64)
02.09 23:10:15 [Server] INFO Loading libraries, please wait...
02.09 23:10:16 [Server] INFO 2020-09-02 23:10:16,912 main WARN Advanced terminal features are not available in this environment
02.09 23:10:21 [Server] INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
02.09 23:10:22 [Server] INFO Reloading ResourceManager: Default, bukkit
02.09 23:10:23 [Server] INFO Loaded 7 recipes
02.09 23:10:25 [Server] INFO Starting minecraft server version 1.16.2
02.09 23:10:25 [Server] INFO Loading properties
02.09 23:10:25 [Server] INFO This server is running Paper version git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
02.09 23:10:25 [Server] INFO Server Ping Player Sample Count: 12
02.09 23:10:25 [Server] INFO Using 4 threads for Netty based IO
02.09 23:10:25 [Server] INFO Debug logging is disabled
02.09 23:10:25 [Server] INFO Default game type: SURVIVAL
02.09 23:10:25 [Server] INFO Generating keypair
02.09 23:10:26 [Server] INFO Starting Minecraft server on 51.89.67.47:25585
02.09 23:10:26 [Server] INFO Using epoll channel type
02.09 23:10:26 [Server] WARN Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
02.09 23:10:31 [Server] WARN Legacy plugin dynmap v3.1-beta-1-367 does not specify an api-version.
02.09 23:10:32 [Server] INFO [dynmap] Loading dynmap v3.1-beta-1-367
02.09 23:10:32 [Server] INFO [dynmap] version=git-Paper-174 (MC: 1.16.2)
02.09 23:10:32 [Server] ERROR [dynmap] Unable to find field g for net.minecraft.server.v1_16_R2.BiomeStorage
02.09 23:10:32 [Server] ERROR [org.bukkit.craftbukkit.v1_16_R2.CraftServer] Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.1-beta-1-367 (Is it up to date?)
02.09 23:10:32 [Server] INFO java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
02.09 23:10:32 [Server] INFO at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[?:?]
02.09 23:10:32 [Server] INFO at org.dynmap.bukkit.helper.v116.BukkitVersionHelperSpigot116.<init>(BukkitVersionHelperSpigot116.java:45) ~[?:?]
02.09 23:10:32 [Server] INFO at org.dynmap.bukkit.Helper.getHelper(Helper.java:38) ~[?:?]
02.09 23:10:32 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:821) ~[?:?]
02.09 23:10:32 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:392) ~[patched_1.16.2.jar:git-Paper-174]
02.09 23:10:32 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.2.jar:git-Paper-174]
02.09 23:10:32 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-174]
02.09 23:10:32 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-174]
02.09 23:10:32 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
02.09 23:10:32 [Server] INFO [Harbor] Loading Harbor v1.6.1
02.09 23:10:32 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
02.09 23:10:32 [Server] INFO Preparing level "world"
02.09 23:10:32 [Server] INFO -------- World Settings For [world] --------
02.09 23:10:32 [Server] INFO Experience Merge Radius: 6.0
02.09 23:10:32 [Server] INFO Cactus Growth Modifier: 100%
02.09 23:10:32 [Server] INFO Cane Growth Modifier: 100%
02.09 23:10:32 [Server] INFO Melon Growth Modifier: 100%
02.09 23:10:32 [Server] INFO Mushroom Growth Modifier: 100%
02.09 23:10:32 [Server] INFO Pumpkin Growth Modifier: 100%
02.09 23:10:32 [Server] INFO Sapling Growth Modifier: 100%
02.09 23:10:32 [Server] INFO Beetroot Growth Modifier: 100%
02.09 23:10:32 [Server] INFO Carrot Growth Modifier: 100%
02.09 23:10:32 [Server] INFO Potato Growth Modifier: 100%
02.09 23:10:32 [Server] INFO Wheat Growth Modifier: 100%
02.09 23:10:33 [Multicraft] Skipped 85 lines due to rate limit (30/s)
02.09 23:10:33 [Server] INFO Loaded 0 spawn chunks for world world
02.09 23:10:33 [Server] INFO Preparing spawn area: 0%
02.09 23:10:33 [Server] INFO Preparing spawn area: 0%
02.09 23:10:33 [Server] INFO Preparing spawn area: 0%
02.09 23:10:34 [Server] INFO Preparing spawn area: 1%
02.09 23:10:34 [Server] INFO Time elapsed: 1772 ms
02.09 23:10:34 [Server] INFO Preparing start region for dimension minecraft:the_nether
02.09 23:10:34 [Server] INFO Loaded 0 spawn chunks for world world_nether
02.09 23:10:34 [Server] INFO Preparing spawn area: 0%
02.09 23:10:35 [Server] INFO Time elapsed: 398 ms
02.09 23:10:35 [Server] INFO Preparing start region for dimension minecraft:the_end
02.09 23:10:35 [Server] INFO Loaded 0 spawn chunks for world world_the_end
02.09 23:10:35 [Server] INFO Time elapsed: 269 ms
02.09 23:10:35 [Server] INFO [dynmap] Enabling dynmap v3.1-beta-1-367*
02.09 23:10:35 [Server] INFO [dynmap] Dynmap is disabled (unsupported platform)
02.09 23:10:35 [Server] INFO [Harbor] Enabling Harbor v1.6.1
02.09 23:10:35 [Server] INFO Running delayed init tasks
02.09 23:10:35 [Server] Startup Done (10.084s)! For help, type "help"
02.09 23:10:35 [Server] INFO Timings Reset
```

**Comment by koppen** [comment]
Everything else seems to be working
